### ISSUE TITLE
Before join a channel user should be able to preview own video and he can off own video and voice before joining a channel.

### ISSUE THREAD

**Issue by saeb-panahifar** [ChapterII/ngx-agora-sdk-ng#5]

**Comment by alibsg** [comment]
Generate a channel and token for the session ,camera preview,  voice preview as an icon on camera video preview overlay , mic and camera icon should be presented on video as overlay 
A join button should be available to join the meeting

**Comment by alibsg** [comment]
@saeb-panahifar I have made a pull request please check the result and inform me whether is it convenient or not.

**Comment by saeb-panahifar** [comment]
Great! Thanks informing me. I will do it today or tomorrow.
